server:
  port: 8081
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timebean?serverTimezone=Asia/Seoul
    username: root
    password: 425375
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  cache:
    type: redis
  session:
    timeout: 3600s
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: 2580

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    org:
      springframework:
        cache: DEBUG
        data:
          redis: DEBUG
